[package]
name = "rust360"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.5" }
wgpu = { version = "*" }
futures = "0.3"
image = "0.25.4"
bytemuck = { version = "1.16", features = [ "derive" ] }

